FROM node:8

ENV redisurl="mqredis.sp0uzb.0001.usw2.cache.amazonaws.com"
ENV redisport=6379

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY package*.json ./

RUN npm install
# If you are building your code for production
# RUN npm ci --only=production

# Bundle app source
COPY . .

EXPOSE 3000
CMD [ "node", "messageserver.js" ]